name: Docker Image CD

on:
  push:
    branches: [main]

jobs:
  continuous-integration:
    uses: Sayuck/Trabalho-Individual-2021-2/.github/workflows/docker-image.yml@main

  deploy:
    needs: continuous-integration

    name: continuous-delivery
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Build and push action
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:aplicacao/docker"
          push: true
          tags: sayuck/biblioteca-gces:latest
