name: Docker Image CI

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create network
        working-directory: ./aplicacao
        run: docker network create biblioteca-network

      - name: Lint
        working-directory: ./aplicacao
        run: docker-compose run aplication bash -c "gem install rubocop; rubocop -A --fail-level F"

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create network
        working-directory: ./aplicacao
        run: docker network create biblioteca-network

      - name: Run tests
        working-directory: ./aplicacao
        run: docker-compose run aplication bash -c "rails db:reset; rspec"

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create network
        working-directory: ./aplicacao
        run: docker network create biblioteca-network

      - name: Run aplication
        working-directory: ./aplicacao
        run: docker-compose up --build -d
